name: AntiAutoclicker
version: '${project.version}'
main: me.naaihr.antiautoclicker.AntiAutoclicker
depend: [ProtocolLib]

commands:
  autoclicker:
    description: gets Autoclicker Statistics
    usage: /<command>